FROM ubuntu:22.04

ENV TZ=Europe/Russia \
	DEBIAN_FRONTEND=noninteractive

RUN apt update 
RUN apt install -y \
    git \
    git-lfs \
    curl \
    jq \
    bash \
    build-essential \
    python3 \
    valgrind \
    cppcheck \
    clang \
    gcovr \
	valgrind \
	check
